new Pull Request
PashkovAlexey/SecondTest pull request #1
Opened 2022-01-13 19:23 UTC by Ozoonee

list check it

2022-01-13 19:25 UTC, PashkovAlexey commented
I think it's ok

2022-01-14 19:45 UTC, mtghunt requested changes

2022-01-14 19:45 UTC, mtghunt commented on src/Bandit.java
> +    }
нужно код комментировать

2022-01-14 19:45 UTC, mtghunt commented on src/Bandit.java
> +    }
нет модификатра доступа  double stealMoney;

2022-01-14 19:59 UTC, PashkovAlexey commented on src/Bandit.java
>      double stealMoney;
добавить здесь private, геттеры и сеттеры уже есть внизу

2022-01-14 20:14 UTC, PashkovAlexey commented on src/Bandit.java
> +    private double stealMoney;
now it's perfect

2022-01-14 20:18 UTC, PashkovAlexey commented on src/Bandit.java
> +    private double stealMoney;
so here you see the private

2022-01-14 20:21 UTC, PashkovAlexey commented on src/Bandit.java
> +
here the getter

2022-01-14 20:24 UTC, PashkovAlexey commented on src/Bandit.java
> +    private double stealMoney;
now everything is ok

2022-01-14 20:26 UTC, PashkovAlexey commented on src/Bandit.java
> +    }
Александр сделал

2022-01-29 08:21 UTC, merged